### ISSUE TITLE
Wine 1.8.7

### ISSUE THREAD

**Issue by LeCharlatan** [PlayOnLinux/WineBuild#1]
Hello,
I was wondering if that's possible to get Wine 1.8.7 on PlayOnLinux
Since this is the latest version of the 1.8.x branch

Thanks

**Comment by Isakku** [comment]
I was going to ask a similar question. I see that PlayOnLinux shows the list to choose wine versions to install, but lately many wine versions (specially staging versions) are missing there! Why? What's wrong?

**Comment by LeCharlatan** [comment]
Seems that nobody never answer here :p

**Comment by qparis** [comment]
In fact, be reassured the project is still very active. You are just asking your question on the old winebuild repository which is no longer used.

Feel free to ask your question here: https://github.com/PhoenicisOrg/phoenicis-winebuild
Also, If I'm not mistaken, your problem has been solved: https://www.playonlinux.com/wine

**Comment by LeCharlatan** [comment]
Hi @qparis 
Well... that explains why... lol
Thanks for the information

Edit : The base of the problem hasn't been solved, since it misses Wine 1.8.7 stable :D

**Comment by Isakku** [comment]
I had to update my PlayOnLinux version to see changes. Only then the list of available Wine versions began to update in a more consistent way. But to be able to update I needed the repositories to be updated as well. Thankfully they were updated some time ago.

**Comment by qparis** [comment]
> Hi @qparis
> Well... that explains why... lol
> Thanks for the information
> 
> Edit : The base of the problem hasn't been solved, since it misses Wine 1.8.7 stable :D

Why do you need wine 1.8.7 in 2019 :-) 



> I had to update my PlayOnLinux version to see changes. Only then the list of available Wine versions began to update in a more consistent way. But to be able to update I needed the repositories to be updated as well. Thankfully they were updated some time ago.

This is perfectly normal :)

**Comment by Isakku** [comment]
> This is perfectly normal :)

Normal when the makers of the software update the repos available for all distros they support. But they didn't have a Ubuntu xenial repo for quite a long time, being a Mint user, that affected me. I had to use Lutris all that time.

**Comment by qparis** [comment]
> > This is perfectly normal :)
> 
> Normal when the makers of the software update the repos available for all distros they support. But they didn't have a Ubuntu xenial repo for quite a long time, being a Mint user, that affected me. I had to use Lutris all that time.

Well, this is a mistake but all the repos are copy of each other. So the distribution name is not important.

**Comment by LeCharlatan** [comment]
Hi @qparis 

Can close this issue now, no ?
