### ISSUE TITLE
A request - Could you add those builds?

### ISSUE THREAD

**Issue by Ahmed-E-86** [PlayOnLinux/WineBuild#2]
There is a new project that builds Wine-staging-esync, and Proton builds that can be used with Playonlinux.

https://github.com/Kron4ek/Wine-Builds

Could you add these builds to your collection?

**Comment by qparis** [comment]
Hi! Yes we can.
I'm just redirecting you here: https://github.com/PhoenicisOrg/phoenicis-winebuild/ :)

**Comment by Ahmed-E-86** [comment]
Ok. Thanks.
